export const EVENT_TYPES = {
  // Appointment events
  APPOINTMENT_BOOKED: 'APPOINTMENT_BOOKED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',
  
  // Prescription events
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  PRESCRIPTION_CANCELLED: 'PRESCRIPTION_CANCELLED',
  
  // Pharmacy events
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  LOW_STOCK: 'LOW_STOCK',
  
  // Payment events
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
} as const;

export type EventType = typeof EVENT_TYPES[keyof typeof EVENT_TYPES];
